model_path: "/home/gandalf/MIA/runs/Feb26_15-48-32_gandalf-MS-7845_avi"

# model class, e.g. UNet3D, ResidualUNet3D
model_name: ir_csn_152_
# model configuration

model:
  # number of output classes (output channels)
  classes: 2
  in_channels: 3
  
# Data loader configuration
loaders:
  #dimension order
  model_dim_order: CH_D_H_W # used for csn models
  backend: 'costum' # costum | monai
  format: 'nifty'
  task_type: "image2scalar"
  task: 'costum'
  TestdataRoot: '/home/gandalf/MIA/data/kinetics400_tiny_train_nifty/data'
  TestdataCSV: '/home/gandalf/MIA/data/kinetics400_tiny_train_nifty/data.csv'

  batchSize: 1
  Resize_height: 224
  Resize_width: 224
  Resize_depth: -1

  Crop_height: 224
  Crop_width: 224
  Crop_depth: 32
  numWorkers: 1

  
  
  # validation method 
  val_method:
    type: 'image_lvl+saliency_maps' # "patch_lvl" | 'image_lvl' | 'image_lvl+saliency_maps'
    samples: 10 # number of samples for validation if patch_lvl
    nr_saliency: 10

# loss function configuration
loss:
  # loss function to be used during training
  name: ['CE']
# evaluation metric configuration
eval_metric:
  name: ['acc_top_1']

