# use a fixed random seed to guarantee that when you run the code twice you will get the same outcome
manual_seed: 0
# PyTorch configuration
local_rank: 1


# model configuration
model:
# model class, e.g. UNet3D
  dimension: 2D+T
  encoder_depth: 4
  in_channels: 3
  feat_dim: 2048
  num_proj_layers: 2
  backbone: r3d_18
  num_classes: 2
  pretrain_model: 'None'
  pretrain_encoder: 'None'
# Data loader configuration
task_type: "representation_learning"
loaders:
  #dimension order
  format: 'nifty'
  store_memory: False
  use_amp: True
  

  CropForeGround: False
  isCT: False

  Resize_height: 224
  Resize_width: 224
  Resize_depth: -1

  Crop_height: 128
  Crop_width: 128
  Crop_depth: 32
  batchSize: 16

  mode: training
  numWorkers: 3

  # validation method 
  val_method:
    type: "patches" # patches | sliding
    samples: 1

# trainer configuration
trainer:
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: null
  # how many iterations between validations
  validate_frequency: 10
  # max number of epochs
  epochs: 800

# optimizer configuration
# optimizer configuration
optimizer:
  type: "sgd" # 
  # initial learning rate
  learning_rate: 0.12 # 0.05*BS/256 -> 0.1 if BS=512
  # weight decay
  weight_decay: 0.0005 #5e-4 
  momentum: 0.9

lr_scheduler:
  type: "cos" # NOT IMPLEMENTED JET
  lr_warmup_epochs: 10
  gamma: 0.2
# loss function configuration
loss:
  # loss function to be used during training
  name: ['Siam'] #CE_pixel CE_pixel
# evaluation metric configuration
eval_metric_train:
  name: []
eval_metric_val:
  name: ['knn_acc_top_1']
# learning rate scheduler configuration
