model_path: "/home/gandalf/MIA/runs/Mar11_16-17-57_gandalf-MS-7845_avi" #"/home/gandalf/segmento/runs/Jan19_14-08-51_gandalf-MS-7845_avi"

# model class, e.g. UNet3D, ResidualUNet3D
model_name: UNet3D

# Configurations
model:
  dimensions: 3
  # number of input channels to the model
  in_channels: 1
  # number of output classes (output channels)
  classes: 5
  # determines the order of operators in a single layer (gcr - GroupNorm+Conv3d+ReLU)
  layer_order: gcr
  # feature maps scale factor
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8

# Data loader configuration
loaders:
  task_type: 'image2image'
  task: 'costum'
  use_amp: True
  format: "nifty"

  TestdataRoot: '/media/gandalf/AE3416073415D2E7/CHAOS_pancreas_MRI_nifty/Task038_CHAOS_Task_3_5_Variant2'
  TestdataCSV: '/media/gandalf/AE3416073415D2E7/CHAOS_pancreas_MRI_nifty/Task038_CHAOS_Task_3_5_Variant2/val.csv'

  isCT: False
  CropForeGround: False
  batchSize: 1 # NOT IMPLEMENTED FOR BATCH SIZE>1
  pixdim_height: 1.62109375
  pixdim_width: 1.62109375
  pixdim_depth: 7.52999983
  height: 192
  width: 192
  depth: 32

  numWorkers: 3
  val_method:
    type: 'sliding_window'

# loss function configuration
loss:
  # loss function to be used during training
  name: ['diceCE_loss']
# evaluation metric configuration
eval_metric:
  name: [dice_class, dice_global]
# learning rate scheduler configuration
