model_path: "/home/gandalf/MIA/runs/Mar17_10-07-29_gandalf-MS-7845_avi" #"/home/gandalf/segmento/runs/Jan19_14-08-51_gandalf-MS-7845_avi"

# model class, e.g. UNet3D, ResidualUNet3D
model_name: UNet3D

# Configurations
model:
  dimensions: 3
  # number of input channels to the model
  in_channels: 4
  # number of output classes (output channels)
  classes: 4
  # determines the order of operators in a single layer (gcr - GroupNorm+Conv3d+ReLU)
  layer_order: gcr
  # feature maps scale factor
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8

# Data loader configuration
loaders:
  task_type: 'image2image'
  task: 'costum'
  format: nifty

  TestdataRoot: '/home/gandalf/MIA/data/BRATS_nifty_small'
  TestdataCSV: '/home/gandalf/MIA/data/BRATS_nifty_small/train.csv'

  isCT: False
  CropForeGround: False
  batchSize: 1 # NOT IMPLEMENTED FOR BATCH SIZE>1
  full_size: False
  # In full size is not true upsampling from the following size will be performed
  pixdim_height: 1.5
  pixdim_width: 1.5
  pixdim_depth: 2
  height: 128
  width: 128
  depth: 64

  numWorkers: 3
  mode: testing
  val_method:
    type: 'sliding_window'
# loss function configuration
loss:
  # loss function to be used during training
  name: ['diceCE_loss']
# evaluation metric configuration
eval_metric:
  name: [dice_class, dice_global]
# learning rate scheduler configuration
